CREATE TABLE CUSTOMER 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(50) NOT NULL 
, SURNAME VARCHAR2(50) NOT NULL 
, BIRTH_DATE DATE NOT NULL 
, CONSTRAINT CUSTOMER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
