CREATE TABLE MONTHLY_PAYMENT 
(
  ID NUMBER NOT NULL 
, CREDIT_ID NUMBER NOT NULL 
, PAYMENT_DATE DATE NOT NULL 
, BASE_AMOUNT NUMBER NOT NULL 
, INTEREST_AMOUNT NUMBER NOT NULL 
, TOTAL_AMOUNT NUMBER NOT NULL 
, CONSTRAINT MONTHLY_PAYMENT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE MONTHLY_PAYMENT
ADD CONSTRAINT MONTHLY_PAYMENT_FK1 FOREIGN KEY
(
  CREDIT_ID 
)
REFERENCES CREDIT
(
  ID 
)
ENABLE;
